[build]
  command = "npm build"
  publish="https://github.com/mzteepowell/to-do-list/tree/master/to-do-list/build"
  base = "https://github.com/mzteepowell/to-do-list/tree/master/to-do-list"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200